# -*- coding: utf-8 -*-
"""Bibliotheek_n.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f2rC7ib63HOhvrMNgOMb2hKgt4JP6r9N
"""
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import interpolate as ip
from openpyxl import load_workbook
from scipy.integrate import cumulative_trapezoid as cumtrapz
"""
Dit is onze bibliotheek met onze globale variabelen. Ondertussen lekker leeg, zoals het hoort blijkbaar.
"""
GRAVITATION_CONSTANT = 9.81
E = 205*(10**9)
WATERDICHTHEID = 1025
STAALGEWICHT = 7850
WEIGHT_STAAL = 2.1*GRAVITATION_CONSTANT*STAALGEWICHT
WEIGHT_WATER = GRAVITATION_CONSTANT*WATERDICHTHEID
VLOEIGRENS = 190*(10**6)