# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G-sXpUqh5OyhBPD9JASW5oewU2wkMasI
"""

import pandas as pd
import numpy as np

def calculateSpiegel(arr_gewicht, dataframe, huiddikte):
  fg_totaal = dataframe.iloc[0,1]*huiddikte*9.81*7850
  fg_per_cm = fg_totaal/50
  for i in range(50):
    arr_gewicht[i] += fg_per_cm
  return arr_gewicht