# -*- coding: utf-8 -*-
"""Momenten-/krachtensom2functie.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pkCDoe6w95Md0Kch56jQn5NDcZidp_2F
"""

import numpy as np

def momentensom2(momentensom1, locatietank1, zwaartetank1):
  """
  Deze functie neemt de eerste momentensom (waarmee de vulling van tank 1 bepaald is) en voegt hier de momenten
  veroorzaakt door de tank aan toe. De momentensom (zowel de input als output) is een array met drie elements: het moment rond de x-
  as,y-as en z-as.
  """
  tweedemomentensom = momentensom1+np.cross(np.array(locatietank1), np.array([0,0,-zwaartetank1]))
  return tweedemomentensom

def krachtsom2(krachtsom1, dic, plaatdikte, staalgewicht):
  """
  Deze functie neemt de eerste krachtsom en voegt hier het gewicht van de bulkheads van tank 2 aan toe.
  """
  oppervlakte_bh_tank2 = 0
  for x in dic:
    oppervlakte_bh_tank2 += dic[x][0]
  tweedekrachtsom = krachtsom1 + (oppervlakte_bh_tank2*plaatdikte*staalgewicht)
  return tweedekrachtsom